CREATE TABLE IF NOT EXISTS ROOMS (
  ID TEXT PRIMARY KEY,
  LOCATION TEXT,
  PLAYER_COUNT INTEGER,
  CREATED_AT INTEGER,
  LAST_UPDATED_AT INTEGER
  );

CREATE INDEX IF NOT EXISTS ROOMS_PLAYER_COUNT ON ROOMS (
  PLAYER_COUNT
  );

CREATE INDEX IF NOT EXISTS ROOMS_LOCATION ON ROOMS (
  LOCATION
  );
